# Callibration for Gent

In [2]:
import cv2
from ultralytics import YOLO


model = YOLO("../yolov8n.pt")
camera = cv2.VideoCapture("D:/nike downloads/Antwerpen_07-05_1400-1500/Nike Antwerpen_ch2_20240506140000_20240506143000.mp4")
img_counter = 0

while True:
    ret, frame = camera.read()

    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        img_path = "../callibration_frames/Frame_{}.jpg".format(img_counter)
        cv2.imwrite(img_path, frame)
        outs = model.predict(frame)
        boxes = outs[0].boxes
        extracted_counter = 0
        for i in range(len(boxes)):
            feet = [float(boxes[i].xyxy[0][2] - ((boxes[i].xyxy[0][2] - boxes[i].xyxy[0][0]) /2)), float(boxes[i].xyxy[0][3])]
            display(feet)
            feet = [int(x) for x in feet]
            colored_frame = cv2.circle(frame, (feet[0], feet[1]), radius=1, color=(0,255,0), thickness=2)
            named_frame = cv2.putText(colored_frame, str(feet), (feet[0] + 10, feet[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 1, cv2.LINE_AA)
            x=int(boxes[i].xyxy[0][0].item())
            y=int(boxes[i].xyxy[0][1].item())
            w=int(boxes[i].xyxy[0][2].item())
            h=int(boxes[i].xyxy[0][3].item())
            display(x, y, w, h)
            extracted_image = frame[y:h,x:w]
            display(extracted_image.size)
            if extracted_image.size > 0:
                cv2.imshow("valid", extracted_image)
                cv2.resizeWindow("valid", 600, 600)
                extracted_counter += 1
                extracted_image_path = "../callibration_frames/Frame_{}_{}.jpg".format(img_counter, extracted_counter)
                cv2.imwrite(extracted_image_path, extracted_image)
        cv2.imwrite(img_path, named_frame)
        img_counter += 1

camera.release()


0: 384x640 11 persons, 3 suitcases, 89.5ms
Speed: 4.0ms preprocess, 89.5ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


[720.4019165039062, 999.85205078125]

617

612

823

999

239166

[1966.7950439453125, 445.60504150390625]

1925

147

2008

445

74202

[2145.97412109375, 545.794921875]

2087

232

2204

545

109863

[432.7463073730469, 547.9089965820312]

348

316

517

547

117117

[984.0540771484375, 849.0216064453125]

894

463

1073

849

207282

[601.3551025390625, 454.3695068359375]

545

229

657

454

75600

[1314.107177734375, 516.4038696289062]

1249

398

1378

516

45666

[216.78530883789062, 863.028564453125]

151

636

281

863

88530

[669.9852294921875, 310.15325927734375]

633

143

706

310

36573

[2358.85888671875, 541.039794921875]

2324

306

2393

541

48645

[341.12353515625, 730.5284423828125]

233

421

448

730

199305

[152.33151245117188, 906.4309692382812]

59

646

245

906

145080

[1071.8314208984375, 442.987548828125]

1041

370

1102

442

13176

[290.182373046875, 1267.17578125]

221

1113

359

1267

63756


0: 384x640 11 persons, 2 suitcases, 76.2ms
Speed: 2.3ms preprocess, 76.2ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)


[721.157470703125, 1004.9002685546875]

617

612

824

1004

243432

[1967.338623046875, 443.21356201171875]

1926

149

2008

443

72324

[2140.07568359375, 547.0527954101562]

2085

219

2194

547

107256

[983.89697265625, 849.7601318359375]

892

462

1075

849

212463

[731.7022705078125, 419.52032470703125]

678

192

784

419

72186

[2434.015625, 567.4492797851562]

2325

210

2542

567

232407

[229.02366638183594, 877.010986328125]

157

625

300

877

108108

[445.98651123046875, 548.6080322265625]

374

306

516

548

103092

[600.2916259765625, 439.9630126953125]

541

230

659

439

73986

[1315.483642578125, 515.4745483398438]

1252

399

1378

515

43848

[291.7586669921875, 1266.9080810546875]

224

1114

359

1266

61560

[2161.06640625, 540.6309814453125]

2089

186

2232

540

151866

[2200.59716796875, 396.05364990234375]

2167

155

2233

396

47718

Escape hit, closing...


In [7]:
import cv2
from ultralytics import YOLO
import numpy as np


model = YOLO("../model_- 15 april 2024 18_14.pt")
camera = cv2.VideoCapture("D:/nike downloads/Antwerpen_07-05_1400-1500/Nike Antwerpen_ch4_20240506140000_20240506143000.mp4")
img_counter = 0
allpoints=[]
while True:
    ret, frame = camera.read()

    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test10", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        img_path = "../callibration_frames/Frame_{}.jpg".format(img_counter)
        cv2.imwrite(img_path, frame)
        outs = model.predict(frame)
        boxes = outs[0].boxes
        for i in range(len(boxes)):
            print(boxes)
            feet = [float(boxes[i].xyxy[0][2] - ((boxes[i].xyxy[0][2] - boxes[i].xyxy[0][0]) /2)), float(boxes[i].xyxy[0][3])]
            display(feet)
            allpoints.append(feet)
            feet = [int(x) for x in feet]
            frame = cv2.circle(frame, (feet[0], feet[1]), radius=1, color=(0,255,0), thickness=2)
            frame = cv2.putText(frame, str(feet), (feet[0] + 10, feet[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 1, cv2.LINE_AA)
            # named_frame = cv2.rectangle(named_frame, (boxes[i].xywh[0], boxes[i].xywh[1]),boxes[i].xywh[0] + boxes[i].xywh[2],  boxes[i].xywh[1] + boxes[i].xywh[3])
        cv2.imshow("valid", frame)
        cv2.imwrite(img_path, frame)
        img_counter += 1

camera.release()


0: 384x640 5 Persons, 80.3ms
Speed: 3.1ms preprocess, 80.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0.])
conf: tensor([0.8161, 0.7455, 0.7094, 0.4920, 0.4325])
data: tensor([[1.4501e+03, 1.4301e+02, 1.5552e+03, 4.2609e+02, 8.1614e-01, 0.0000e+00],
        [4.4150e+02, 3.9799e+02, 5.8581e+02, 6.6987e+02, 7.4548e-01, 0.0000e+00],
        [3.5015e+02, 4.0613e+02, 4.7366e+02, 7.1206e+02, 7.0942e-01, 0.0000e+00],
        [7.2226e+02, 4.6421e+02, 9.1423e+02, 8.6517e+02, 4.9203e-01, 0.0000e+00],
        [6.2228e+02, 3.1490e+02, 7.5346e+02, 6.6580e+02, 4.3254e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1440, 2560)
shape: torch.Size([5, 6])
xywh: tensor([[1502.6918,  284.5486,  105.1006,  283.0757],
        [ 513.6538,  533.9267,  144.3103,  271.8774],
        [ 411.9041,  559.0912,  123.5120,  305.9296],
        [ 818.2432,  664.6897,  191.9669,  400.9519],
        [ 6

[1502.6917724609375, 426.0864562988281]

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0.])
conf: tensor([0.8161, 0.7455, 0.7094, 0.4920, 0.4325])
data: tensor([[1.4501e+03, 1.4301e+02, 1.5552e+03, 4.2609e+02, 8.1614e-01, 0.0000e+00],
        [4.4150e+02, 3.9799e+02, 5.8581e+02, 6.6987e+02, 7.4548e-01, 0.0000e+00],
        [3.5015e+02, 4.0613e+02, 4.7366e+02, 7.1206e+02, 7.0942e-01, 0.0000e+00],
        [7.2226e+02, 4.6421e+02, 9.1423e+02, 8.6517e+02, 4.9203e-01, 0.0000e+00],
        [6.2228e+02, 3.1490e+02, 7.5346e+02, 6.6580e+02, 4.3254e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1440, 2560)
shape: torch.Size([5, 6])
xywh: tensor([[1502.6918,  284.5486,  105.1006,  283.0757],
        [ 513.6538,  533.9267,  144.3103,  271.8774],
        [ 411.9041,  559.0912,  123.5120,  305.9296],
        [ 818.2432,  664.6897,  191.9669,  400.9519],
        [ 687.8700,  490.3458,  131.1777,  350.9016]])
xywhn: tensor([[0.5870, 0.1976, 0.0411, 0.1966],
        [0.2006, 0.3708, 0.0564, 0

[513.65380859375, 669.8654174804688]

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0.])
conf: tensor([0.8161, 0.7455, 0.7094, 0.4920, 0.4325])
data: tensor([[1.4501e+03, 1.4301e+02, 1.5552e+03, 4.2609e+02, 8.1614e-01, 0.0000e+00],
        [4.4150e+02, 3.9799e+02, 5.8581e+02, 6.6987e+02, 7.4548e-01, 0.0000e+00],
        [3.5015e+02, 4.0613e+02, 4.7366e+02, 7.1206e+02, 7.0942e-01, 0.0000e+00],
        [7.2226e+02, 4.6421e+02, 9.1423e+02, 8.6517e+02, 4.9203e-01, 0.0000e+00],
        [6.2228e+02, 3.1490e+02, 7.5346e+02, 6.6580e+02, 4.3254e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1440, 2560)
shape: torch.Size([5, 6])
xywh: tensor([[1502.6918,  284.5486,  105.1006,  283.0757],
        [ 513.6538,  533.9267,  144.3103,  271.8774],
        [ 411.9041,  559.0912,  123.5120,  305.9296],
        [ 818.2432,  664.6897,  191.9669,  400.9519],
        [ 687.8700,  490.3458,  131.1777,  350.9016]])
xywhn: tensor([[0.5870, 0.1976, 0.0411, 0.1966],
        [0.2006, 0.3708, 0.0564, 0

[411.9041442871094, 712.0560302734375]

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0.])
conf: tensor([0.8161, 0.7455, 0.7094, 0.4920, 0.4325])
data: tensor([[1.4501e+03, 1.4301e+02, 1.5552e+03, 4.2609e+02, 8.1614e-01, 0.0000e+00],
        [4.4150e+02, 3.9799e+02, 5.8581e+02, 6.6987e+02, 7.4548e-01, 0.0000e+00],
        [3.5015e+02, 4.0613e+02, 4.7366e+02, 7.1206e+02, 7.0942e-01, 0.0000e+00],
        [7.2226e+02, 4.6421e+02, 9.1423e+02, 8.6517e+02, 4.9203e-01, 0.0000e+00],
        [6.2228e+02, 3.1490e+02, 7.5346e+02, 6.6580e+02, 4.3254e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1440, 2560)
shape: torch.Size([5, 6])
xywh: tensor([[1502.6918,  284.5486,  105.1006,  283.0757],
        [ 513.6538,  533.9267,  144.3103,  271.8774],
        [ 411.9041,  559.0912,  123.5120,  305.9296],
        [ 818.2432,  664.6897,  191.9669,  400.9519],
        [ 687.8700,  490.3458,  131.1777,  350.9016]])
xywhn: tensor([[0.5870, 0.1976, 0.0411, 0.1966],
        [0.2006, 0.3708, 0.0564, 0

[818.2431640625, 865.1656494140625]

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0.])
conf: tensor([0.8161, 0.7455, 0.7094, 0.4920, 0.4325])
data: tensor([[1.4501e+03, 1.4301e+02, 1.5552e+03, 4.2609e+02, 8.1614e-01, 0.0000e+00],
        [4.4150e+02, 3.9799e+02, 5.8581e+02, 6.6987e+02, 7.4548e-01, 0.0000e+00],
        [3.5015e+02, 4.0613e+02, 4.7366e+02, 7.1206e+02, 7.0942e-01, 0.0000e+00],
        [7.2226e+02, 4.6421e+02, 9.1423e+02, 8.6517e+02, 4.9203e-01, 0.0000e+00],
        [6.2228e+02, 3.1490e+02, 7.5346e+02, 6.6580e+02, 4.3254e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1440, 2560)
shape: torch.Size([5, 6])
xywh: tensor([[1502.6918,  284.5486,  105.1006,  283.0757],
        [ 513.6538,  533.9267,  144.3103,  271.8774],
        [ 411.9041,  559.0912,  123.5120,  305.9296],
        [ 818.2432,  664.6897,  191.9669,  400.9519],
        [ 687.8700,  490.3458,  131.1777,  350.9016]])
xywhn: tensor([[0.5870, 0.1976, 0.0411, 0.1966],
        [0.2006, 0.3708, 0.0564, 0

[687.8699951171875, 665.796630859375]

Escape hit, closing...


: 

In [ ]:
extracted_image.size

197640

# Enlarge groundplan

In [ ]:
import cv2

image = cv2.imread("../groundplan/Nike antwerpen.png")

bigger = cv2.resize(image, (800, 2000), interpolation = cv2.INTER_LINEAR)
cv2.imwrite("../groundplan/Nike_antwerpen_enlarged.png", image)

True

# Callibration camera 2

In [7]:
# provide points from image 1
pts_src = np.array([[1131, 762], [287, 472], [77, 925],[1750, 939], [1058, 529], [68, 415]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2381, 544],[2352, 238],[2222, 387],[2389, 647], [2431,481], [2330, 29]
                    ])

# calculate matrix H
h2, status2 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[68, 415]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h2)
pointsOut

array([[[2329.712   ,   33.647762]]], dtype=float32)

# Callibration for camera 3

In [8]:
# provide points from image 1
pts_src = np.array([[1629, 154], [1135, 534], [1998, 1186],[238, 609], [271, 277], [923, 405], [1068, 155]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2330, 29],[2222, 387],[2381, 544],[2034, 455], [1763,181], [2134, 328], [2130, 68]
                    ])

# calculate matrix H
h3, status2 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[230, 730]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h3)
pointsOut

array([[[     2057.1,      510.56]]], dtype=float32)

# Callibrate camera 4

In [1]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[490, 650], [1704, 1200], [2059, 455], [1863, 136], 
                    # [962, 1373], [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1975, 704],[2034, 455],[1700, 417], [1359, 525],
                    #  [88,258], [27, 223]
                    ])

# calculate matrix H
h4, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[490, 650]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h4)
pointsOut

array([[[1975.,  704.]]], dtype=float32)

# Callibrate camera 5

In [17]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[468, 604], [1584, 224], [118, 797], [1251, 384], [1029, 1113]
                    # [465, 476]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2132, 324],[1840, 151],[2224, 358],[1986, 208], [2215,142]
                    # [2084,337]
                    # [27, 223]
                    ])

# calculate matrix H
h5, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1029, 1113]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h5)
pointsOut

array([[[     2216.5,      142.96]]], dtype=float32)

# Callibrate camera 6

In [8]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[919, 1311], [886, 427], [313, 1305], [19, 438], 
                    # [219, 808], 
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1840, 151],[1674, 415],[1909, 206],[1920, 706], 
                    # [1879,334], 
                    # [27, 223]
                    ])

# calculate matrix H
h6, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[274, 808]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h6)
pointsOut

array([[[1887.5697 ,  341.45087]]], dtype=float32)

# Callibrate camera 7

In [25]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1605, 926], [425, 494], [316, 1368],  [2152, 630], [146, 135], [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1984, 238],[1702, 415],[2031, 455], [1973,35], [406, 747], [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h7, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h7)
pointsOut

array([[[765.7831, 220.3334]]], dtype=float32)

# Callibrate camera 8

In [12]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1317, 337], [2172, 898], [2173, 467], [2080, 340], [279, 53], 
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1700, 413],[2032, 455],[1909, 240],[1842, 151], [467,618], 
                    # [27, 223]
                    ])

# calculate matrix H
h8, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[286, 116]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h8)
pointsOut

array([[[921.6831, 646.8048]]], dtype=float32)

# Callibrate camera 9

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[626, 509], [1917, 110], [1108, 382], [2389, 177],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1428, 415],[2034, 455],[1556, 432],[2392, 647],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 10

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1399, 107], [2050, 377], [1175, 303], [1871, 3],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1907, 236],[1671, 415],[1691, 144],[2376, 647],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 11

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[130, 916], [963, 367], [2343, 323], [1228, 35],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1438, 415],[1287, 708],[609, 804],[1202, 706],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 12

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[127, 518], [1910, 429], [1398, 349], [2553, 798],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[689, 354],[1272, 208],[1091, 199],[1434, 415],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 13

In [15]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[916, 263], [718, 271], [391, 284], [834, 209],[46, 313], [1273, 1160]
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[449, 437],[469, 505],[467, 669],[373, 503],[408, 1031], [833, 251]
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[154, 277]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[334.74234, 977.9425 ]]], dtype=float32)

# Callibrate camera 14

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1739, 239], [2072, 161], [1622, 196], [2021, 140],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[960, 195],[1274, 238],[958, 142],[1274, 208],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 15

In [5]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[775, 445], [993, 393], [2266, 582], [2542, 626],[2232,984]
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[807, 1033],[740, 1036],[471, 802],[408, 749],[609,747]
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1919, 586]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[4124.901, 3554.158]]], dtype=float32)

# Callibrate camera 16

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[472, 379], [754, 285], [2187, 589], [853, 219],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[408, 747],[469, 675],[873, 728],[469, 618],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 17

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[864, 389], [2278, 233], [775, 579], [585, 1102],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[379, 439],[956, 142],[375, 505],[377, 620],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 18

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[915, 1129], [1246, 1111], [1731, 1069], [1473, 165],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[467, 507],[434, 505],[377, 503],[373, 675],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)

# Callibrate camera 19

In [ ]:
#TODO

import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1532, 585], [1822, 877], [1693, 1320], [1147, 1149],
                    #  [376, 699], [272, 384]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[899, 723],[962, 778],[964, 854],[892, 859],
                    #  [1388,435], [1379, 251]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[913, 806]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9) 
pointsOut

array([[[ 27.230206, 222.00674 ]]], dtype=float32)