In [ ]:
import cv2

image = cv2.imread("../groundplan/Nike antwerpen.png")

bigger = cv2.resize(image, (800, 2000), interpolation = cv2.INTER_LINEAR)
cv2.imwrite("../groundplan/Nike_antwerpen_enlarged.png", image)

# Camera 1 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[792, 372], [226, 612], [1151, 539],  [679, 318],
                    #  [146, 135], [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[150, 425],[146, 678],[270, 423], [69,425],
                    #  [406, 747], [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h1, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h1)
pointsOut

# Camera 2 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[813, 353], [1142, 510], [401, 215],  [978, 182], [156, 231], [287, 164]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[301, 685],[146, 678],[582, 687], [299,892], [805, 578], [800, 699]
                    # [27, 223]
                    ])

# calculate matrix H
h2, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h2)
pointsOut

# Camera 3 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[458, 457], [815, 209], [891, 569],  [347, 401],
                    #  [146, 135], [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[143, 727],[150, 425],[300, 700], [83,729],
                    #  [406, 747], [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h3, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h3)
pointsOut

# Camera 4 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[248, 223], [434, 209], [266, 467],  [923, 477], [535, 74], 
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[804, 576],[800, 700],[584, 699], [583,910], [1087, 970],
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h4, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h4)
pointsOut

# Camera 5 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1770, 172], [2265, 259], [1343, 1292],  [2044, 976], [535, 74], 
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[801, 579],[799, 686],[634, 482], [661,571], [1087, 970],
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h5, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h5)
pointsOut

# Camera 6 en 7 overbodig?



# Camera 8 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[982, 766], [1272, 277], [1611, 765],  [1328, 200], [775, 481], [748, 244], [1497, 14],
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1086, 698],[1414, 694],[1099, 817], [1529,699], [1257, 567], [1529, 415], [2193, 734],
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h8, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h8)
pointsOut

# Camera 9 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1621, 109], [1291, 1052], [600, 989],  [409, 698],
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[584, 685],[1102, 685],[1112, 800], [1040, 904],
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h9, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[588, 112]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h9)
pointsOut

# Camera 10 callibration

In [1]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1801, 713], [1023, 873], [714, 1390],  [1302, 118], [2116, 251],  [386, 761],
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1586, 809],[1529, 685],[1425, 695], [1966, 534], [1776, 860],  [1542, 430],
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h10, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[708, 408]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h10)
pointsOut

array([[[1741.2793,  367.1124]]], dtype=float32)

# Camera 11 callibration

In [2]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[2348, 764], [1852, 996], [323, 40],  [1139, 24], [2202, 338],  
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1584, 808],[1529, 685],[2049, 150], [1966, 534], [1776, 860], 
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h11, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1500, 170]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h11)
pointsOut

array([[[1868.1427 ,  659.43555]]], dtype=float32)

# Camera 12 callibration

In [4]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1203, 531], [737, 405], [781, 219],  [568, 181], [443, 983],  [1409, 745],[2132, 1300]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1257, 568],[1305, 686],[1235, 819], [1289, 900], [1418, 526], [1267, 504],[ 1270, 357]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h12, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1700, 1300]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h12)
pointsOut

array([[[1312.7802 ,  391.25662]]], dtype=float32)

# Camera 13 callibration

In [6]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1477, 627], [1113, 427], [2446, 1036],  [327, 1405], [1835, 873]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1597, 255],[1627, 191],[1521, 416], [1436, 110], [1555, 304]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1750, 1100]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

array([[[1502.3668,  298.5468]]], dtype=float32)

# Camera 14 callibration

In [10]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1454, 943], [1120, 251], [40, 545],  [990, 881], [754, 1263],[719, 557], [2462, 779]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2046, 577],[2047, 148],[1603, 280], [1966, 535], [1913, 631], [1892, 378], [2321, 605]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[2100, 1100]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

array([[[2174.5374,  652.5441]]], dtype=float32)

# Camera 15 missing

# Camera 16 callibration

In [14]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[934, 1104], [2146, 504], [2356, 705],  [2063, 1341], [1614, 495],[772, 1280], [2241, 429], [2242, 1603], [700, 1900]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2145, 744],[1553, 696],[1708, 511], [2081, 543], [1776, 853], [2191, 731], [1302, 694], [2090, 447], [2300, 617]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

array([[[1641.8363 ,  849.09216]]], dtype=float32)

# Camera 17 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1034, 576], [714, 626], [821, 1262],  [1279, 1164], 
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[1900, 162],[1878, 107],[1758, 143], [1772, 201], 
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

# Camera 18 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1473, 436], [1722, 448], [1350, 995],  [1734, 989], [1733,705]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2771, 747],[2703, 760],[2697, 554], [2640, 584], [2662, 647]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

# Camera 19 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[513, 1930], [218, 428], [2303, 465],  [2440, 960], 
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2718, 214],[3364, 164],[2843, 678], [2688, 468], 
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

# Camera 20 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1093, 1362], [721, 942], [1516, 1102],  [317, 1053], 
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[2692, 216],[2666, 144],[2718, 210], [2587, 141], 
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

# Camera 21 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[1693, 492], [2196, 295], [867, 463],  [754, 291], [2094, 343], [316, 1411]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[3087, 340],[2690, 469],[3251, 414], [3260, 580], [2843, 407], [3347, 183]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

# Camera 22 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[270, 1354], [1594, 419], [2297, 583],  [1737, 860], [1590,1592]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[3393, 758],[2956, 538],[3087, 350], [3268, 588], [3423, 630]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut

# Camera 23 callibration

In [ ]:
import cv2 # import the OpenCV library
import numpy as np # import the numpy library

# provide points from image 1
pts_src = np.array([[619, 463], [416, 570], [948, 254],  [1372, 564], [265,1279]
                    # [1994, 539]
                    # [913, 806]
                    ])
# corresponding points from image 2 (i.e. (154, 174) matches (212, 80))
pts_dst = np.array([[3053, 520],[2958, 537],[3249, 428], [3094, 679], [2845,693]
                    #  [1918, 35]
                    # [27, 223]
                    ])

# calculate matrix H
h13, status1 = cv2.findHomography(pts_src, pts_dst)

# provide a point you wish to map from image 1 to image 2
a = np.array([[1800, 450]], dtype='float32')
a = np.array([a])

# finally, get the mapping
pointsOut = cv2.perspectiveTransform(a, h13)
pointsOut